x-common-env: &common-env
  TZ: "America/Sao_Paulo"


services:
  zookeeper:
    image: kafka_zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      <<: *common-env
    command: >
      bash -c "$$KAFKA_HOME/bin/zookeeper-server-start.sh $$KAFKA_HOME/config/zookeeper.properties"
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper_data:/var/lib/zookeeper
      - ./zookeeper_logs:/var/log/zookeeper
    networks:
      kafka_network:
        ipv4_address: 172.28.0.10

  kafka:
    image: kafka_zookeeper:latest
    container_name: kafka
    hostname: kafka
    environment:
      <<: *common-env
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    command: >
      bash -c "
        sed -i 's|zookeeper.connect=.*|zookeeper.connect=zookeeper:2181|' $$KAFKA_HOME/config/server.properties &&
        sed -i 's|#listeners=PLAINTEXT://:9092|listeners=PLAINTEXT://0.0.0.0:9092|' $$KAFKA_HOME/config/server.properties &&
        echo 'advertised.listeners=PLAINTEXT://172.28.0.11:9092' >> $$KAFKA_HOME/config/server.properties &&
        $$KAFKA_HOME/bin/kafka-server-start.sh $$KAFKA_HOME/config/server.properties
      "
    volumes:
      - ./kafka_data:/var/lib/kafka/data
      - ./kafka_logs:/var/log/kafka
    networks:
      kafka_network:
        ipv4_address: 172.28.0.11

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"

    depends_on:
      - kafka
      - zookeeper
      - ksqldb-server
    environment:
      <<: *common-env
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_KSQLDBSERVER: "http://ksqldb-server:8088"
    networks:
      kafka_network:
        ipv4_address: 172.28.0.12
    volumes:
      - ./kafka_ui_data:/etc/kafka-ui

  # ðŸ§  ksqlDB Server
  # ðŸ§© ksqlDB Server com autenticaÃ§Ã£o BASIC inline
  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    container_name: ksqldb-server
    depends_on:
      - kafka
    ports:
      - "8088:8088"
      - "8081:8081"
    environment:
      <<: *common-env

      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"

      # Timeouts
      KSQL_REQUEST_TIMEOUT_MS: 300000
      KSQL_STREAMS_REQUEST_TIMEOUT_MS: 300000
      KSQL_STREAMS_METADATA_MAX_AGE_MS: 30000
      KSQL_STREAMS_MAX_PROCESSING_MS: 300000
      KSQL_STREAMS_PROCESSING_TIMEOUT_MS: 300000
      KSQL_STREAMS_COMMIT_INTERVAL_MS: 500000
      KSQL_STREAMS_NUM_STREAM_THREADS: 2
      KSQL_STREAMS_CACHE_MAX_BYTES_BUFFERING: 0

      # Push Query v2 (correto)
      KSQL_SHARED_RUNTIME_ENABLED: "true"
      KSQL_QUERY_PUSH_V2_ENABLED: "true"
      KSQL_QUERY_PUSH_V2_REGISTRY_INSTALLED: "true"

      # Rede e timeouts extras
      KSQL_STREAMS_SOCKET_CONNECTION_SETUP_TIMEOUT_MAX_MS: 30000
      KSQL_STREAMS_RETRY_BACKOFF_MS: 50000
      KSQL_STREAMS_RECONNECT_BACKOFF_MS: 50000

      # Pull queries
      KSQL_QUERY_PULL_INTERNAL_TIMEOUT_MS: 300000
      KSQL_QUERY_PULL_TABLE_SCAN_ENABLED: "true"
      KSQL_QUERY_PULL_ENABLE_STALE_READS: "true"

      # DiretÃ³rio de extensÃµes (UDFs)
      KSQL_KSQL_EXTENSION_DIR: "/opt/ksql/ext/"
    volumes:
      - ./udf:/opt/ksql/ext/

    networks:
      kafka_network:
        ipv4_address: 172.28.0.14

  # ðŸ’» ksqlDB CLI autenticado
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:latest
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
    environment:
      <<: *common-env
      KSQL_SERVER_URL: "http://ksqldb-server:8088"
    networks:
      kafka_network:



# ðŸŒ Rede
networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# ðŸ’¾ Volumes persistentes
volumes:
  zookeeper_data:
  zookeeper_logs:
  kafka_data:
  kafka_logs:
  kafka_ui_data:
  ksqldb_state:
  ksqldb_config:
