services:
  zookeeper:
    image: kafka_zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    command: >
      bash -c "$$KAFKA_HOME/bin/zookeeper-server-start.sh $$KAFKA_HOME/config/zookeeper.properties"
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper_data:/var/lib/zookeeper
      - ./zookeeper_logs:/var/log/zookeeper
    networks:
      kafka_network:
        ipv4_address: 172.28.0.10

  kafka:
    image: kafka_zookeeper:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    command: >
      bash -c "
        sed -i 's|zookeeper.connect=.*|zookeeper.connect=zookeeper:2181|' $$KAFKA_HOME/config/server.properties &&
        sed -i 's|#listeners=PLAINTEXT://:9092|listeners=PLAINTEXT://0.0.0.0:9092|' $$KAFKA_HOME/config/server.properties &&
        echo 'advertised.listeners=PLAINTEXT://172.28.0.11:9092' >> $$KAFKA_HOME/config/server.properties &&
        $$KAFKA_HOME/bin/kafka-server-start.sh $$KAFKA_HOME/config/server.properties
      "
    volumes:
      - ./kafka_data:/var/lib/kafka/data
      - ./kafka_logs:/var/log/kafka
    networks:
      kafka_network:
        ipv4_address: 172.28.0.11

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"

    depends_on:
      - kafka
      - zookeeper
      - ksqldb-server
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
      KAFKA_CLUSTERS_0_KSQLDBSERVER: "http://ksqldb-server:8088"
    networks:
      kafka_network:
        ipv4_address: 172.28.0.12
    volumes:
      - ./kafka_ui_data:/etc/kafka-ui

  # üß† ksqlDB Server
  # üß© ksqlDB Server com autentica√ß√£o BASIC inline
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.29.0
    container_name: ksqldb-server
    depends_on:
      - kafka
    ports:
      - "8088:8088"
      - "8081:8081"
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
    networks:
      kafka_network:
        ipv4_address: 172.28.0.14

  # üíª ksqlDB CLI autenticado
  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
    environment:
      KSQL_SERVER_URL: "http://ksqldb-server:8088"
    networks:
      kafka_network:
        ipv4_address: 172.28.0.15

  ksqldb-ui:
    image: deniskrumko/ksqldb-ui:latest
    environment:
      APP_CONFIG: /config.toml
    volumes:
      - ./development.toml:/config.toml
    ports:
      - "8082:8080"
    depends_on:
      - ksqldb-server
    networks:
      kafka_network:
        ipv4_address: 172.28.0.16


# üåê Rede
networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# üíæ Volumes persistentes
volumes:
  zookeeper_data:
  zookeeper_logs:
  kafka_data:
  kafka_logs:
  kafka_ui_data:
  ksqldb_state:
  ksqldb_config:
